services:
  flask-app:
    volumes:
      - ./flask-app:/app
      - ./flask-app/logs:/app/logs
    command: python run.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DEBUG_METRICS=1

  react-app:
    ports:
      - "10.50.57.107:3000:3000"
