global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # 1. Сам Prometheus
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Flask API приложение
  - job_name: 'flask-app'
    metrics_path: '/metrics' # Экспортируется через prometheus_flask_exporter
    static_configs:
      - targets: ['flask-app:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'flask-api'

  # 3. Метрики ОС (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # 4. База данных PostgreSQL
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # 5. Кэш Redis
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # 6. Метрики Docker контейнеров (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']